### ISSUE TITLE
Tables overlap table of contents

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#1237]
Table 85 wraps poorly when I'm not viewing the following page in a full-sized window:
https://www.elastic.co/guide/en/elasticsearch/reference/master/transform-search.html

![image](https://user-images.githubusercontent.com/26471269/66000921-47d4eb00-e455-11e9-84fd-988422112d09.png)

Is this something we can address?

**Comment by nik9000** [comment]
It looks like this is fixed actually. I'm not sure who did it though.

**Comment by nik9000** [comment]
@lcawl, could you double check/

**Comment by lcawl** [comment]
I still see the problem when the browser window isn't full size.

**Comment by nik9000** [comment]
> I still see the problem when the browser window isn't full size.

I see it now!
