### ISSUE TITLE
There is a link broken to the azure marketplace. Go here--> https://www.elastic.co/guide/index.html and scroll down to “Subscribe” and click on ‘Azure Marketplace’ (404 error) #1388

### ISSUE THREAD

**Issue by lisatrosh** [elastic/docs#2730]
There is a link broken to the azure marketplace. Go here--> https://www.elastic.co/guide/index.html and scroll down to “Subscribe” and click on ‘Azure Marketplace’ (404 error)

Specifics (e.g., OS, Hardware, Browser, etc.): Chrome

![image (6)](https://github.com/elastic/docs/assets/114245362/46f6bd07-2e59-4c62-a237-6e6467b09231)
![image (5)](https://github.com/elastic/docs/assets/114245362/7a730a24-a27a-4025-a79b-70ff0e260495)

**Comment by jrodewig** [comment]
Thanks @lisatrosh.

This looks to be related to some third-party tool we're using. When I disable JavaScript in Chrome, the link works correctly.

**Comment by jrodewig** [comment]
Thanks @lisatrosh. I'm currently looking into the problem with the web team. I'll update this issue again once we have a solution or I have more info.

**Comment by jrodewig** [comment]
This is fixed now. Thanks, @lisatrosh.

**Comment by lisatrosh** [comment]
Hey @jrodewig I am still not seeing it fixed, is this normal? can you try testing it with your team as I am still receiving an error. Thanks in advance!

**Comment by jrodewig** [comment]
Hi @lisatrosh. It looks to be working on my end. I've checked on a few different machines. You may want to try clearing your browser cache and reloading the page.

Thanks again for raising this!

![link-fix](https://github.com/elastic/docs/assets/40268737/c0d06a9e-3328-4aef-88b4-0510783b69f7)

**Comment by lisatrosh** [comment]
Thanks for the clarification @jrodewig! Have a great Thursday!
